// 스토리
const stories = {
    1: [{ speaker: "senior", text: "무안군 인간 쉘터의 검문소에서 일하게 된 걸 축하해.", expression: "murfy-smile"},
        { speaker: "senior", text: "어떤 일을 하는지는 알고 있나?", expression: "murfy-talk"},
        { speaker: "player", text: "네, 인간과 안드로이드를 구분해서 인간만을 통과시켜야 합니다!", expression: "yuri-response"},
        { speaker: "senior", text: "그래, 맞아. 인간만을 대피소에 들이고, 인간인 척 하는 인공지능 로봇들은 전부 내쫓는 것." , expression: "murfy-smile"},
        { speaker: "senior", text: "그들을 구분하는 기준은 딱 하나야." , expression: "murfy-talk"},
        { speaker: "senior", text: "외관상의 차이." , expression: "murfy-default", illustration: { show: "img/story/1.png" }},
        { speaker: "senior", text: "인공지능 로봇은 대부분 기계 부품이 겉으로 드러나 있어.", expression: "murfy-hmm" },
        { speaker: "senior", text: "벗겨진 피부 사이로 회색의 차가운 몸체가 보인다든가, 팔이 철골로 이루어져 있다든가...", expression: "murfy-hmm" },
        { speaker: "senior", text: "인간인 것 같다면 초록색 버튼을 눌러 문을 열어줘.",expression: "murfy-default", illustration: { show: "img/story/2.png" }},
        { speaker: "senior", text: "안드로이드라고 판단된다면, 빨간색 버튼을 눌러.",expression: "murfy-default", illustration: { show: "img/story/3.png" }},
        { speaker: "senior", text: "안드로이드를 우리 쉘터에 들이지 않도록 주의 깊게 관찰하도록 해.",expression: "murfy-talk", illustration: { hide: true }},
        { speaker: "senior", text: "행운을 빌어.",expression: "murfy-smile"}],

    2: [{ speaker: "senior", text: "어제의 일은 어땠어? 어렵지 않았지?", expression: "murfy-smile"},
        { speaker: "senior", text: "안타깝게도, 오늘은 확인해야 할 게 추가됐어.", expression: "murfy-default"},
        { speaker: "senior", text: "이 신문 보여? 강원도 영월군의 로봇 연구소에서 심각한 오염물질 누출 사고가 있었대.", expression: "murfy-hmm", illustration: { show: "img/story/4.png" }},
        { speaker: "senior", text: "그러니 신분증을 확인해서, 강원도 출신의 방문자는 들여보내면 안될 것 같아.", expression: "murfy-hmm"},
        { speaker: "player", text: "저, 제가 아직 한국의 지리에 익숙하지 않습니다만...", expression: "yuri-flustered"},
        { speaker: "senior", text: "그럴 줄 알고 내가 준비했지. 자, 한국 지도야.", expression: "murfy-smile", illustration: { show: "img/story/5.png" }},
        { speaker: "senior", text: "손가락으로 드래그하면 지도를 움직일 수 있어. 확대하면 세부적인 지역 이름까지 다 볼수 있고.", expression: "murfy-talk"},
        { speaker: "senior", text: "명심해, 강원도 출신의 방문자 전부야! 연구소가 있는 영월군뿐만 아니라, 원주나 정선, 강릉 등 강원도 출신의 방문자는 전부 피폭되었을 가능성이 있으니 받아주면 안돼!", expression: "murfy-hmm"},
        { speaker: "player", text: "며, 명심하겠습니다!", expression: "yuri-response"},
        { speaker: "senior", text: "좋아, 어제도 잘 했으니 오늘도 잘 할 수 있을 거야.", expression: "murfy-smile"},
        { speaker: "senior", text: "자, 시작하지.", expression: "murfy-default"}],

    3: [{ speaker: "senior", text: "좋은 아침.", expression: "murfy-smile"},
        { speaker: "senior", text: "한국 지도에는 좀 익숙해졌어?", expression: "murfy-talk"},
        { speaker: "player", text: "여러 번 보다 보면 나아질 것 같습니다!", expression: "yuri-response"},
        { speaker: "senior", text: "기세 좋은데? 그럼 체크해야 할 기준이 더 늘어도 괜찮겠지?", expression: "murfy-smile"},
        { speaker: "player", text: "네? 어, 어떤...", expression: "yuri-flustered"},
        { speaker: "senior", text: "부산과 울산에 있는 로봇 연구소에서도 방사능 사고가 있었다고 해. 어제 들어온 따끈따끈한 제보야.", expression: "murfy-hmm", illustration: { show: "img/story/6.png" }},
        { speaker: "senior", text: "그러니까, 부산과 울산 출신의 방문자는 재량껏 전부 거절해야 하는 건 알겠지?", expression: "murfy-hmm"},
        { speaker: "player", text: "강원도, 부산, 울산... 알겠습니다.", expression: "yuri-default"},
        { speaker: "senior", text: "아, 그리고 상부에서 명령이 내려왔어.", expression: "murfy-talk"},
        { speaker: "senior", text: "이제 무작정 외관과 출신지만 보고 거르지 말고, 말을 걸어봐야 한다나?", expression: "murfy-hmm"},
        { speaker: "senior", text: "간혹 성대기관이 고장난 로봇이 있대. '아아-안- 녀엉-' 이렇게 말한다는데. ", expression: "murfy-hmm", illustration: { show: "img/story/7.png" }},
        { speaker: "player", text: "그럼 모든 이들에게 말을 걸어봐야 하는 건가요?", expression: "yuri-flustered"},
        { speaker: "senior", text: "뭐, 전부 걸 필요는 없지. 로봇이 확실한 애들한테까지 물어볼 필요는 없잖아!", expression: "murfy-smile"},
        { speaker: "senior", text: "아, 진짜 마지막.", expression: "murfy-default"},
        { speaker: "senior", text: "신분증에 만료기한 좀 확인해줘.", expression: "murfy-default", illustration: { show: "img/story/8.png" }},
        { speaker: "senior", text: "2126년 이전에 발급된 카드들은 모조품일 가능성이 있으니 전부 거절해야 한대.", expression: "murfy-default"},
        { speaker: "player", text: "그럼 2126년에 발급된 카드도 거절해야 하는 겁니까?", expression: "yuri-default"},
        { speaker: "senior", text: "이젠 척하면 척이네! 맞아, 2126년 이전에 발급된 카드라면 거절하면 돼.", expression: "murfy-smile"},
        { speaker: "senior", text: "자, 그럼 오늘도... 수고하라고!", expression: "murfy-default"}],

    4: [{ speaker: "senior", text: "하루라도 좀 평온하게 흘러가면 좋을 텐데, 그치?" ,expression: "murfy-smile"},
        { speaker: "player", text: "또 무슨 일이 생겼습니까?" ,expression: "yuri-flustered"},
        { speaker: "senior", text: "서울과학기술대학교의 연구소에서 안드로이드들이 대거 탈출하는 일이 발생했어.", expression: "murfy-hmm", illustration: { show: "img/story/9.png" }},
        { speaker: "senior", text: "문제는, 죄다 최신형 로봇들이라 지금으로선 육안으로 인간인지 아닌지 구분이 안 간다는 거지...", expression: "murfy-hmm"},
        { speaker: "senior", text: "그러니 어쩌겠어? 서울 출신의 방문자는 전부 돌려보낼 수밖에.", expression: "murfy-default"},
        { speaker: "player", text: "강원도, 부산, 울산, 서울-", expression: "yuri-flustered"},
        { speaker: "senior", text: "하하, 그래도 좋은 소식! 강원도에 국지적인 비가 내려서, 오염물질들이 전부 씻겨내려갔다네.", expression: "murfy-smile", illustration: { show: "img/story/10.png" }},
        { speaker: "senior", text: "그러니까 강원도 출신 사람들은 이제 다시 받아도 돼.", expression: "murfy-default"},
        { speaker: "player", text: "듣던 중 반가운 소리네요.", expression: "yuri-default"},
        { speaker: "senior", text: "그렇지? ...맞아, 이걸 까먹을 뻔했네!", expression: "murfy-hmm"},
        { speaker: "senior", text: "번거롭겠지만, 로봇 외형을 한 사람들 중에서 팔만 로봇인 사람들은 재차 확인해줘.", expression: "murfy-hmm", illustration: { show: "img/story/11.png" }},
        { speaker: "player", text: "확인이요?", expression: "yuri-hmm"},
        { speaker: "senior", text: "우리나라는 팔만 의수인 사람이 꽤 있잖아?", expression: "murfy-talk"},
        { speaker: "senior", text: "팔이 기계라 안드로이드인줄 알고 내쫓았는데, 알고 보니 사이보그였던 인간일 수도 있단 말씀.", expression: "murfy-talk"},
        { speaker: "senior", text: "그러니까 팔만 의수인 사람들은 왜 팔이 기계인지 질문을 하도록 해.", expression: "murfy-default"},
        { speaker: "senior", text: "정당한 이유가 있다면 들여보내고, 그게 아니라면... 알지? 내쫓아버려.", expression: "murfy-smile"},
        { speaker: "player", text: "알겠습니다!", expression: "yuri-response"},
        { speaker: "senior", text: "좋아, 난 네가 일을 잘 하고 있다는 걸 알아. 매번 고마워.", expression: "murfy-smile"},
        { speaker: "player", text: "해야 할 일을 했을 뿐입니다.", expression: "yuri-response"},
        { speaker: "senior", text: "......", expression: "murfy-default", illustration: { hide: true }},
        { speaker: "senior", text: "한 가지 물어볼 게 있는데...", expression: "murfy-talk"},
        { speaker: "senior", text: "만약 로봇의 칩만을 골라내어 폭파하는 전자파가 있다고 한다면...?", expression: "murfy-hmm"},
        { speaker: "senior", text: "넌 그 전자파를 작동시킬거야?", expression: "murfy-hmm"},
        { speaker: "player", text: "저는 기술과학 쪽은 잘 모릅니다만…", expression: "yuri-flustered"},
        { speaker: "player", text: "작동시킬 것 같습니다, 지금도 안드로이드들로 인해 많은 피해를 입고 있고…", expression: "yuri-default"},
        { speaker: "senior", text: "폭발의 범위가 동 일대를 날려버릴 수준이라고 해도?.", expression: "murfy-hmm"},
        { speaker: "player", text: "그, 그럼 안될 것 같습니다! 그래도 밖에 남아있는 인간이 있지 않습니까.", expression: "yuri-what"},
        { speaker: "senior", text: "역시 다들 그렇게 생각하는건가… ", expression: "murfy-hmm"},
        { speaker: "player", text: "......?", expression: "yuri-default"},
        { speaker: "senior", text: "아무것도 아니야. 자자, 일하러 가라고!", expression: "murfy-smile"},
    ],

    5: [{ speaker: "senior", text: "어제도 일을 정말 완벽하게 해냈더군!" ,expression: "murfy-smile"},
        { speaker: "senior", text: "솔직히, 좀 감탄했어. 이렇게 잘 구분해낼 줄 몰랐거든.", expression: "murfy-talk"},
        { speaker: "senior", text: "먼저 고맙다고 말해두지. 이 프로젝트의 1등공신은 너야.", expression: "murfy-smile"},
        { speaker: "player", text: "과찬이십... 예?", expression: "yuri-hmm"},
        { speaker: "player", text: "어떤 프로젝트를 말씀하시는 겁니까?", expression: "yuri-flustered"},
        { speaker: "senior", text: "'노아의 방주 작전.'", expression: "murfy-evil"},
        { speaker: "player", text: "....?", expression: "yuri-what"},
        { speaker: "senior", text: "사실 이 연구소, 인간을 보호하기 위해 만들어진 게 아냐.", expression: "murfy-eviltalk", illustration: { show: "img/story/12.png" }},
        { speaker: "senior", text: "밖에 남은 인간, 로봇... 연구소 밖의 인원들을 전부 몰살하기 위해서 만들어진거지." ,expression: "murfy-eviltalk"},
        { speaker: "senior", text: "실은, 어제 말했던 '로봇의 칩을 폭발시키는 전자파'를 개발했어. " ,expression: "murfy-evil"},
        { speaker: "player", text: "잠시만요! 그 전자파를 작동시키면 다른 생존자들도 피해를 입지 않겠습니까?!", expression: "yuri-startled"},
        { speaker: "senior", text: "이 보호소가 왜 핵방공호를 개조해서 만들었는지 모르겠어?." ,expression: "murfy-evilsmiletalk"},
        { speaker: "senior", text: "오늘이 지나면, 난 이 전자파를 작동시켜서 한국을 완전히 쑥대밭으로 만들거야." ,expression: "murfy-evilsmile", illustration: { show: "img/story/13.png" }},
        { speaker: "player", text: "노, 농담이 지나치십니다!", expression: "yuri-startled"},
        { speaker: "senior", text: "농담이라니! 이 연구소는 인간을 보호하기 위해 만들어진 게 아냐." ,expression: "murfy-eviltalk"},
        { speaker: "senior", text: "밖에 남은 인간, 로봇... 연구소 밖의 인원들을 전부 몰살하기 위해서 만들어진거지." ,expression: "murfy-evil"},
        { speaker: "senior", text: "이 세상은 글러먹었어. 매일같이 서로가 로봇인지 아닌지를 의심하고, 그 때마다 싸움을 일으키지.", expression: "murfy-hmm"},
        { speaker: "senior", text: "그러니까... 이 세상을 처음부터 다시 시작할 수 밖에 없어." ,expression: "murfy-default"},
        { speaker: "senior", text: "모두가 인간이었던 그 시절로." ,expression: "murfy-default"},
        { speaker: "senior", text: "아무도 서로를 의심할 필요가 없는... 평화로운 시대로." ,expression: "murfy-talk"},
        { speaker: "player", text: "......" ,expression: "yuri-what"},
        { speaker: "senior", text: "왜 안 웃고 있어? 넌 살아남을 거야, 그것도 방공호 안의 살아남을 인원들을 선별한 일등공신으로." ,expression: "murfy-smile"},
        { speaker: "senior", text: "아, 오늘 바뀐 점을 말해주는 것을 까먹었군.", expression: "murfy-default"},
        { speaker: "senior", text: "무안군을 포함한 전라남도, 그리고 광주 사람들을 제외하면 전부 받지 말도록 해.", expression: "murfy-evilsmiletalk", illustration: { show: "img/story/14.png" }},
        { speaker: "senior", text: "마지막 날인데, 위험 요인을 늘릴 필요는 없겠지!", expression: "murfy-evilsmile"},
        { speaker: "senior", text: "아, 그렇지만 인천에서 왔다면 출신지 질문을 통해 다시 한 번 재검문해줘.", expression: "murfy-default", illustration: { show: "img/story/15.png" }},
        { speaker: "senior", text: "오늘 인천공항에서 이 연구소에 필요한 구호품들을 수송해 온 군인들이 도착했다고 했었거든...", expression: "murfy-talk"},
        { speaker: "player", text: "......", expression: "yuri-flustered2"},
        { speaker: "senior", text: "그러니 그 사람들은 꼭 받아줘.", expression: "murfy-smile"},
        { speaker: "senior", text: "여태껏 정말 수고했어.", expression: "murfy-talk"},
        { speaker: "senior", text: "마지막 날도... 잘 부탁해.", expression: "murfy-evildark"}],
};

// 엔딩 스토리
const endings = {
    normal: [
        { speaker: "senior", text: "인간만 남은 지구를 만든 소감은 어때?.", expression: "murfy-default"},
        { speaker: "player", text: "......", expression: "yuri-dark"},
        { speaker: "senior", text: "왜 그렇게 굳어있어? 오늘 같은 기쁜 날에는 샴페인을 뜯어야지.", expression: "murfy-smile", illustration: { show: "img/story/16.png" } },
        { speaker: "senior", text: "고맙게도, 어제 받아온 물자 중에 샴페인이 몇 병 있더라고.", expression: "murfy-talk"},
        { speaker: "player", text: "......", expression: "yuri-dark"},
        { speaker: "senior", text: "영 재미없는 녀석이네, 이거.", expression: "murfy-smile"},
        { speaker: "senior", text: "밖에 남아있던 사람들이 신경쓰이는 거야?", expression: "murfy-hmm"},
        { speaker: "senior", text: "나도 마음이 아파. 이왕이면 안드로이드만 죽일 수 있었으면 더 좋았을 텐데......", expression: "murfy-hmm"},
        { speaker: "player", text: "......", expression: "yuri-dark" },
        { speaker: "senior", text: "그렇지만, 이미 한 번 오염된 세상은 원래대로 되돌릴 수 없다는 걸 네가 이해해줬으면 해.", expression: "murfy-closed", illustration: { show: "img/story/17.png" }},
        { speaker: "senior", text: "이런 방법을 쓰지 않았다면, 넌 오늘도 눈 앞의 이들을 바라보며 끊임없이 의심하고 또 의심해야 했겠지.", expression: "murfy-closed" },
        { speaker: "senior", text: "하지만 이젠 그럼 의심을 할 필요가 없잖아?", expression: "murfy-smile" },
        { speaker: "senior", text: "이 방공호 안의 사람들은 전부 인간이야.", expression: "murfy-default" },
        { speaker: "senior", text: "인류를 오염시키는 인공지능은 더 이상 없어.", expression: "murfy-default" },
        { speaker: "player", text: "......", expression: "yuri-dark" },
        { speaker: "senior", text: "새로운 세상이 시작된거야.", expression: "murfy-closed" },
        { speaker: "senior", text: "아주 평화로운 세상이.", expression: "murfy-closed", illustration: { hide: true }}
    ],
    robot: [
        { speaker: "senior", text: "제길, 제길, 제길...", expression: "murfy-no", illustration: { show: "img/story/18.png" }},
        { speaker: "senior", text: "어째서 방공호 안에 로봇들이 넘쳐나고 있는 거야?!", expression: "murfy-what"},
        { speaker: "senior", text: "이래선 전자파를 작동시킬 수가 없잖아...!", expression: "murfy-no" },
        { speaker: "senior", text: "검문관!", expression: "murfy-what", illustration: { show: "img/story/19.png" }},
        { speaker: "senior", text: "너 일처리를 대체 어떻게 한 거야?!", expression: "murfy-what" },
        { speaker: "player", text: "......", expression: "yuri-hmm" },
        { speaker: "senior", text: "나의 작전을 그렇게 망치고 싶었어?", expression: "murfy-no" },
        { speaker: "senior", text: "그래, 넌 이해를 못 하겠지.", expression: "murfy-startled" },
        { speaker: "senior", text: "매일같이 서로가 인공지능인지 의심하고, 싸워야 하는 사람들의 마음을...!", expression: "murfy-startled" },
        { speaker: "player", text: "아닙니다.", expression: "yuri-talk" },
        { speaker: "player", text: "저도 마찬가지로 이 사회는 잘못되었다고 생각합니다.", expression: "yuri-talk" },
        { speaker: "senior", text: "그럼 왜...", expression: "murfy-no" },
        { speaker: "player", text: "그렇지만, 당신의 방식은 미봉책일 뿐입니다.", expression: "yuri-hmm", illustration: { show: "img/story/20.png" }},
        { speaker: "player", text: "이미 오염된 세상을 돌릴 수는 없다면, 우리가 그에 맞춰 최선을 택해 행동할 수밖에 없다고요.", expression: "yuri-default" },
        { speaker: "player", text: "세상 사람 전부를 의심하며 살아가야 한다고 해도, 다른 이들을 전부 버리고 미련하게 홀로 살아남고 싶지 않습니다.", expression: "yuri-default" },
        { speaker: "senior", text: "......", expression: "murfy-no" },
        { speaker: "player", text: "......", expression: "yuri-flustered2" },
        { speaker: "player", text: "수사대가 올 겁니다.", expression: "yuri-talk" },
        { speaker: "player", text: "이 방공호를 버리고 도망치시던지, 혹은 이곳에 남아 그들의 의사에 굴복할지... 알아서 하시고.", expression: "yuri-talk" },
        { speaker: "player", text: "이만 가겠습니다.", expression: "yuri-hmm" },
        { speaker: "player", text: "그동안 감사했습니다.", expression: "yuri-smile" },
    ]
};

// 캐릭터 정보
const characters = {
    senior: {name: "소장", portrait: "senior"},
    player: {name: "검문관", portrait: "player"}
};


